extends "res://scripts/main.gd"
func qa_flow() -> void:
	assert(world.save_path.is_empty())
	await get_tree().create_timer(0.4).timeout
	life_panel.open("衣橱")
	assert(life_panel.actions.wear_scarf.disabled)
	await capture("artifacts/g8-locked-wardrobe.png")
	for item in Content.ITEMS: world.give(item)
	world.sync_aliases()
	for id in World.OUTFITS:
		life_panel.open("衣橱")
		await qa_click(life_panel.actions["wear_" + id])
		assert(world.data.outfit == id and worn_outfit == id)
		life_panel.hide()
		await capture("artifacts/g8-outfit-" + id + ".png")
	life_panel.open("衣橱")
	await capture("artifacts/g8-wardrobe.png")
	world.data.postcards = Content.ROUTES.keys()
	world.data.letters = [{"text": "渡轮划过海峡，远处的圆顶映着落日。我在小店挑了一片蓝纹陶，忽然觉得，走得再远，也是在收集回家后想讲给你听的故事。", "title": "落日里的一程渡轮", "destination": "istanbul", "trip": 6, "time": world.clock(), "event_id": "g5_istanbul_ordinary", "rewards": "蓝纹陶片"}]
	life_panel.open("收藏")
	await qa_click(life_panel.actions.gift_goldseed)
	assert("flower" in world.data.plant_styles and "goldseed" in world.data.claimed_room_rewards)
	life_panel.open("小屋")
	await qa_click(life_panel.actions.plant_flower)
	assert("plant" in world.data.equipped)
	life_panel.open("收藏")
	await qa_click(life_panel.actions.postcard_istanbul)
	assert(postcard_view.visible and "渡轮" in postcard_view.message.text)
	await capture("artifacts/g8-postcard.png")
	await qa_click(postcard_view.photo_button)
	assert(postcard_view.large and not postcard_view.text_side.visible)
	await capture("artifacts/g8-postcard-photo.png")
	await qa_click(postcard_view.close_button)
	assert(not postcard_view.visible and life_panel.visible)
	# The thumbnail itself must also open the card through a native pointer event.
	var card_column = life_panel.actions.postcard_creek.get_parent()
	var thumbnail = card_column.get_child(0).get_child(0)
	await qa_click(thumbnail)
	assert(postcard_view.visible and postcard_view.heading.text.contains("溪谷"))
	await qa_click(postcard_view.close_button)
	DisplayServer.window_set_size(Vector2i(960, 600))
	await get_tree().create_timer(0.4).timeout
	life_panel.open("衣橱")
	await qa_click(life_panel.actions.wear_hat)
	await capture("artifacts/g8-wardrobe-960.png")
	life_panel.open("收藏")
	await qa_click(life_panel.actions.postcard_istanbul)
	await capture("artifacts/g8-postcard-960.png")
	await qa_click(postcard_view.close_button)
	print("G8_NATIVE_PASS: locked/earned wardrobe, all outfits, room gift claim/equip, postcard button/thumbnail/zoom/close, 960px; synthetic in-memory data")
	get_tree().quit()
